[package]
name = "atom-tui"
version.workspace = true
edition.workspace = true

[dependencies]
atom-core = { workspace = true }
atom-server = { workspace = true }
atom-tools = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
anyhow = { workspace = true }
once_cell = { workspace = true }
unicode-width = { workspace = true }
image = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
libc = { workspace = true }
regex = { workspace = true }
notify = { workspace = true }
resvg = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util", "macros"] }
tempfile = { workspace = true }
ttf-parser = "0.24.1"
