use std::path::PathBuf;
use std::process::Command;
use std::time::{SystemTime, UNIX_EPOCH};

/// Embeds every `ui/themes/*.json` theme definition into the binary so
/// adding a theme requires only a JSON file, no Rust changes. The
/// generated table lives in `OUT_DIR/themes.rs` (see
/// `render::colors::available_themes`). User-defined themes need no
/// rebuild at all: JSON files dropped into the config `themes/`
/// directory are discovered at runtime.
fn embed_themes() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let themes_dir = match manifest.join("../../ui/themes").canonicalize() {
        Ok(dir) => dir,
        Err(_) => return, // no ui/themes directory: nothing to embed
    };
    println!("cargo:rerun-if-changed={}", themes_dir.display());

    let mut files: Vec<String> = std::fs::read_dir(&themes_dir)
        .expect("ui/themes must be readable")
        .flatten()
        .filter(|entry| entry.path().extension().is_some_and(|ext| ext == "json"))
        .map(|entry| entry.file_name().to_string_lossy().into_owned())
        .collect();
    files.sort();

    let mut out = String::from(
        "// @generated by build.rs from ui/themes/*.json — do not edit.\n\
         pub static EMBEDDED_THEMES: &[(&str, &str)] = &[\n",
    );
    for file in &files {
        let stem = file.strip_suffix(".json").unwrap_or(file);
        let path = themes_dir.join(file);
        out.push_str(&format!(
            "    (\"{stem}\", include_str!({})),\n",
            escape_path(&path)
        ));
    }
    out.push_str("];\n");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    std::fs::write(out_dir.join("themes.rs"), out).expect("write generated themes table");
}

/// include_str! needs a literal path; absolute escaped paths always work.
fn escape_path(path: &std::path::Path) -> String {
    let text = path.to_string_lossy();
    let mut out = String::from("\"");
    for ch in text.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            _ => out.push(ch),
        }
    }
    out.push('"');
    out
}

fn main() {
    embed_themes();
    let mut commit = Command::new("git")
        .args(["rev-parse", "--short=12", "HEAD"])
        .output()
        .ok()
        .filter(|output| output.status.success())
        .and_then(|output| String::from_utf8(output.stdout).ok())
        .map(|commit| commit.trim().to_string())
        .filter(|commit| !commit.is_empty())
        .unwrap_or_else(|| "unknown".to_string());
    if Command::new("git")
        .args(["diff", "--quiet"])
        .status()
        .is_ok_and(|status| !status.success())
    {
        commit.push_str("-dirty");
    }
    let profile = std::env::var("PROFILE").unwrap_or_else(|_| "unknown".to_string());
    let stamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);

    // Cargo re-runs this script only when the package sources change, so
    // ATOM_BUILD_ID is stable across rebuilds of identical sources and
    // changes whenever the code does. atom, atoms, atomdev, and atomsdev
    // all link this one atom-core, so a single build shares one ID —
    // clients compare it with the server's via /api/capabilities to
    // recycle a server built from older code. Keep the ATOM_BUILD format
    // in sync with what the `-help` text advertises.
    println!("cargo:rustc-env=ATOM_BUILD={commit} ({profile})");
    println!("cargo:rustc-env=ATOM_BUILD_ID={commit}.{profile}.{stamp}");
}
