# `atom --hot` reloads this file without compiling Rust.
border = "#272b33"
card_dark = "#151516"
card_light = "#1b1b1b"
secondary = "#b491b0"
primary = "#8cadd1"
primary_dark = "#545e69"
select = "#354455"
background = "#111112"
foreground = "#dee3e8"
muted = "#666666"
muted_extra = "#3d3d3d"
diff_add = "#032615"
diff_del = "#260307"
diff_add_bg = "#10241d"
diff_del_bg = "#271518"
syntax_type = "#e8a07a"
syntax_string = "#d8c9b0"
